name: pch-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref_name }}, ${{ github.workflow }})
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    name: ubuntu-22.04-clang-pch
    if: github.repository == 'dadwow/core' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: clang
          CXX: clang++
          pch: true
